### ISSUE TITLE
Application name parsing error

### ISSUE THREAD

**Issue by ehelbig1** [aws-amplify/learn#243]
I ran into an error, `snsdev-dev already exists`, when trying to create a new project. After a bit of digging it appears that root of the problem is the generation of resource names:

`RoleName: !If [ShouldNotCreateEnvResources, 'boardg891ab340_sns-role', !Join ['',[ 'sns', !Select [3, !Split ['-', !Ref 'AWS::StackName']], '-', !Ref env]]]`

This pattern is present in many location throughout the CloudFormation templates and dictates that there must be a convention followed when naming applications. This convention is not enforced through the CLI when initially creating the project.

A name like `example-app` breaks this convention and can cause issues.

Can the resource name generation algorithm be changed to support additional conventions?

If not, can restrictions on project names be added to the CLI?

**Comment by aspittel** [comment]
Sorry for the slow response on this, if your're still seeing this issue can you post it on the amplify-cli repo? Thank you!
