### ISSUE TITLE
Error in Amplify.Storage.list() example

### ISSUE THREAD

**Issue by boaza** [aws-amplify/learn#287]
I followed the [Storage.list() example](https://docs.amplify.aws/lib/storage/list/q/platform/android), but failed to list public files I uploaded.

Diving into AWS's code, I believe the issue is with the "path" parameter in the example, which should be **""** instead of **"/"**.

    Amplify.Storage.list(
        "/",  // *** this should be ""
        result -> {
            for (StorageItem item : result.getItems()) {
                Log.i("MyAmplifyApp", "Item: " + item.getKey());
            }
        },
        error -> Log.e("MyAmplifyApp", "List failure", error)
        );

**Comment by aspittel** [comment]
Sorry for the slow response on this, it looks like it has been fixed. Thanks for raising the issue!
