### ISSUE TITLE
AWS Amplify CD service don't work with "git push -f <origin> <branch_name>"

### ISSUE THREAD

**Issue by MiqueiasGFernandes** [aws-amplify/learn#299]
The amplify Continuous Deployment service at frontend don't work on following steps:

1. Reset to old commit with `git reset --hard <commit_identifier>`
2. Force push to remote repository with `git push -f <origin> <branch_name>`

The AWS Amplify Console don't start a new deployment progress and don't reconize the "new commit"

**Comment by aspittel** [comment]
Hey, sorry for the very slow response on this - if you're still experiencing this can you create an issue on the amplify-hosting repo? thanks!
