### ISSUE TITLE
Sidebar section - incomplete and incorrectly formatted

### ISSUE THREAD

**Issue by hibler13** [aws-amplify/learn#386]
**Issue**:

This section should be set in the margin as a table. Also, the information is incomplete.

**Comment by aspittel** [comment]
Hey, thanks for leaving this issue - can you expand on what you mean by the sidebar section? is this in a course? Or on the platform itself?

**Comment by hibler13** [comment]
Hi, this issue was in the course itself. When I opened this issue, I was seeing markdown code within the main flow of text indicating that there should be a table in the sidebar. Also, the information being shown within the markdown was incomplete placeholder text.

**Comment by aspittel** [comment]
Can you give a link to the page you are seeing this on?

**Comment by hibler13** [comment]
It looks like the issue might have been resolved since I filed this ticket.

Thanks!

From: Ali Spittel ***@***.***>
Reply-To: aws-amplify/learn ***@***.***>
Date: Tuesday, December 6, 2022 at 12:48 PM
To: aws-amplify/learn ***@***.***>
Cc: "Eagan, Jim" ***@***.***>, Author ***@***.***>
Subject: Re: [aws-amplify/learn] Sidebar section - incomplete and incorrectly formatted (Issue #386)


Can you give a link to the page you are seeing this on?
