### ISSUE TITLE
[Bug] Text refers to wrong field

### ISSUE THREAD

**Issue by ed-norris** [aws-amplify/learn#389]
**Issue**:

On page 5 of the intro tutorial, https://amplify.aws/learn/courses/Fullstack-for-Frontend-Developers-e7319/lessons/5 

Existing text:
Let's do the same for the note text - select the paragraph below the title and set the label to note.title.

Should be:
Let's do the same for the note text - select the paragraph below the title and set the label to note.text.

**Comment by ErikCH** [comment]
This has been updated @ed-norris . Please reopen if you have any other issues.
