### ISSUE TITLE
[Bug] modal class causing issues

### ISSUE THREAD

**Issue by nerdstats** [aws-amplify/learn#397]
**Issue**:
While going through this video "Using AWS Amplify Studio Components Locally" [https://amplify.aws/learn/courses/Fullstack-for-Frontend-Developers-e7319/lessons/8] and utilizing the code provided in the tutorial the app complies successfully but the display on the web browser is blank. I narrowed it down to adding the modal className for UpdateNote and CreateNote. This could also be operator error. Any ideas on how to resolve this issue would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/35906441/205467635-67b58753-fa74-4abe-9ab3-7e8d19b4a40b.png)

**Comment by rubiconjosh** [comment]
Do you have errors in the browser console?
