### ISSUE TITLE
[Bug] Membership site example figma file can not be synced with Amplify studio

### ISSUE THREAD

**Issue by weisisheng** [aws-amplify/learn#399]
**Issue**: Hero section renders error when trying to accept all.  

Exact error is: "An error occurred saving components. Bad control character in string literal in JSON at position 190".

Believe related to the "money bag" icons to the left of the text "For just $99" but not experienced enough with Figma.  Can't remove / replace icon since I don't have editing permissions.

TIA

**Comment by scottyoung** [comment]
Hi @weisisheng,

Thank you for bringing this to our attention.  We currently do not support emojis being imported from Figma.  I don't see a money bags emoji in our AWS Amplify UI Kit.  Can you link me to the membership site file you are working from?

You should be able to get editing permissions by pressing a 'Get a copy' button of the Figma file from Figma.com.  For example, our UI Kit file is located at 
https://www.figma.com/community/file/1047600760128127424
If you visit that URL, and press Get a copy, you will have write access to that file.  You can use this method to remove the emoji from your file and attempt to re-import.
