### ISSUE TITLE
[Bug] Video Three is the wrong one

### ISSUE THREAD

**Issue by akilisosa** [aws-amplify/learn#405]
**Issue**:
Video three on the amplify page doesn't make sense where it is. It is the project set up however it is showing something that has components imported which is the next section.

**Comment by salihgueler** [comment]
Hello @akilisosa thank you for reporting this, which course is this for?

**Comment by joegood** [comment]
It is for the [Build a Membership Website with Amplify, Stripe, and Next.js] course.

**Comment by joegood** [comment]
Essentially, video 3 is a copy of video 9.
