### ISSUE TITLE
Build a Membership Website with Amplify, Stripe, and Next.js || Setup a Next.js Project - Instructions Need Updating

### ISSUE THREAD

**Issue by joegood** [aws-amplify/learn#414]
**Issue**:  Written instructions are not sufficient to continue the lesson.  The default options of the create-next-app tool build out the application in such a way that the other lessons do not apply.

For example, create-next-app recommends using page routing.  That is the default and indicated with a "(recommended)" in the tool.  But, that choice will give you a different folder structure than this demo needs.

Also, create-next-app defaults initially to using TypeScript.  The demo lesson uses JavaScript.  So mentions of "_app.js" are invalid.

**Comment by simongillett** [comment]
Agreed with the above - this "lesson" is not useful at all for the reasons given.

**Comment by ErikCH** [comment]
Thanks, we'll look at this!

**Comment by glgauthier** [comment]
@ErikCH please note that along with this issue, the video shown on the page doesn't match this step of the tutorial as documented in https://github.com/aws-amplify/learn/issues/423 

As a new user to aws (and next.js) this was a bummer of a blocker for me
