### ISSUE TITLE
[Bug] Getting "AmplifyProvider was not found" error

### ISSUE THREAD

**Issue by atkreis** [aws-amplify/learn#437]
**Issue**:

I'm on step 7 of this course: https://amplify.aws/learn/courses/Fullstack-for-Frontend-Developers-e7319/lessons/7

When I run "npm run start" I get this message:

Failed to compile.

Attempted import error: 'AmplifyProvider' is not exported from '@aws-amplify/ui-react' (imported as 'AmplifyProvider').
WARNING in [eslint] 
src/App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

ERROR in ./src/index.js 16:34-49
export 'AmplifyProvider' (imported as 'AmplifyProvider') was not found in '@aws-amplify/ui-react' (possible exports: Accordion, AccountSettings, Alert, Authenticator, Autocomplete, Badge, Breadcrumbs, Button, ButtonGroup, Card, CheckboxField, Collection, ComponentPropsToStylePropsMap, ComponentPropsToStylePropsMapKeys, Divider, DropZone, FieldGroupIcon, FieldGroupIconButton, Fieldset, Flex, Grid, Heading, HighlightMatch, Icon, IconsProvider, Image, Input, Label, Link, Loader, Menu, MenuButton, MenuItem, Message, Pagination, PasswordField, PhoneNumberField, Placeholder, Radio, RadioGroupField, Rating, ScrollView, SearchField, SelectField, SliderField, StepperField, SwitchField, Table, TableBody, TableCell, TableFoot, TableHead, TableRow, Tabs, Text, TextAreaField, TextField, ThemeProvider, ToggleButton, ToggleButtonGroup, View, VisuallyHidden, components, createTheme, defaultDarkModeOverride, defaultTheme, primitives, translations, useAuthenticator, useBreakpointValue, usePagination, useTheme, withAuthenticator)

webpack compiled with 1 error and 1 warning

I have run all previous steps including the "npm i aws-amplify @aws-amplify/ui-react".

I've searched on Google for this error and did not find any results.

Any suggestions please?

My main goal is to build a react-native app using Amplify and DataStore.  I already have my react native app but need the online/offline storage capability, and this training would help as a working example.

Thanks.
Alex

**Comment by coolchigi** [comment]
Good day, I am getting the error as well

**Comment by jtfitzge1** [comment]
It looks like the tutorial is out of date - according to the docs AmplifyProvider was renamed to ThemeProvider and using that instead worked for me to complete the tutorial:
https://ui.docs.amplify.aws/react/theming/theme-provider

**Comment by timngyn** [comment]
Hi everyone this should be fixed in the lesson now. Updated the code snippet to use `ThemeProvider`.
