### ISSUE TITLE
How to Upload images from the Nextjs backend API Route? 

### ISSUE THREAD

**Issue by amalhub** [aws-amplify/learn#450]
Hi Team, 

I'm using Amplify Gen 2 for my NextJS project. 
I have been searching through all the docs but didn't find any example on how to upload files that comes to the NextJS backend API route. I tried the "uploadData" function available from "aws-amplify/storage", but it only works in the frontend implementation and not in the backend because it doesn't have the Authenticator wrapper information at the backend. So my request throws "Unauthorized, Access Denied" error. 

Here is my example route.ts code that throws the error: 
```
import { uploadData } from "aws-amplify/storage";

export async function POST(req: Request) {
  try {
    const formData = await req.formData();
    const image = formData.get("image") as File | null;
    const prisma = await db();

    if (image) {
      const filename = image.name;
      const result = prisma.$transaction(async (tx) => {
        const result = await prisma.image.create({
          data: {
            name: image.name,
          },
        });
        await uploadData({
          data: image,
          path: `images/${filename}`,
        });
        return result;
      });
      return Response.json(
        { message: "Image uploaded", result },
        { status: 200 }
      );
    }
    return Response.json({ message: "No image provided" }, { status: 400 });
  } catch (error) {
    console.error(error);
    return Response.json({ error: "Internal server error" }, { status: 500 });
  }
}
```
The reason why I need to do this on the backend and not in the frontend is because I need to update the database at the same time as a transaction. So if the image upload goes wrong for some connectivity issue, the database update gets rolled back. 
Can someone please help me to figure out the code? How can I authenticate the AWS image upload connection at the NextJS backend?

**Comment by HuiSF** [comment]
Hi @amalhub The Storage category `uploadData` API is currently not working on the server-side of a Next.js app, as [this documentation](https://docs.amplify.aws/gen1/react/build-a-backend/server-side-rendering/nextjs/#supported-apis-for-nextjs-server-side-usage) lists. Could you open a feature request in the [Amplify JS repository](https://github.com/aws-amplify/amplify-js/issues)?

**Comment by amalhub** [comment]
Hi @HuiSF, 

Thanks for the response. It is very unfortunate that this feature is not available right now. It is a very essential feature to ensure proper data sync with the database and S3 content. Otherwise, occasionally the app ends up with orphan data in the S3 bucket. 

Is there any other method or workaround I could implement to upload images from the backend API route until this feature becomes available? 

PS: I opened the feature request: https://github.com/aws-amplify/amplify-js/issues/13636

**Comment by cwomack** [comment]
@amalhub, left comments on the related issues linked above tied to the feature request.  We'll close this issue and ask you to follow #13636 for further updates on supporting the `uploadData` API within Storage for SSR usage.
